Improvments on node example
ZupIT/pact-framework-examples pull request #13
Opened 2020-09-03 18:45 UTC by iannferreirazup

PR referring to task:

https://trello.com/c/F75IjqGz/47-melhorias-nas-pocs-de-node-na-execu%C3%A7%C3%A3o-do-teste

2020-09-03 18:53 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/account-api/.gitignore
> +package-lock.json
É importante mantermos arquivos lock no codebase pois eles garantem que qualquer pessoa que clone o repositório instalem a mesma árvore de dependências com a qual fazemos nosso projeto funcionar no ambiente local.

2020-09-03 18:55 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/account-api/.gitignore
> +package-lock.json
referência: https://docs.npmjs.com/configuring-npm/package-lock-json.html

2020-09-03 18:57 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/prime-account-details-api/.gitignore
> +package-lock.json
remover locks do gitignore

2020-09-03 18:57 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/account-api/.gitignore
> +package-lock.json
remover locks do gitignore

2020-09-03 19:02 UTC, renanrodrigueszup requested changes
vide comentários nos arquivos .gitignore

2020-09-03 19:18 UTC, iannferreirazup commented
@renanrodrigueszup adicionado os arquivos .lock novamente.

2020-09-03 19:27 UTC, renanrodrigueszup submitted a review, later dismissed
good to go!

2020-09-04 12:49 UTC, tonysilvazup commented on example/node/one_consumer_two_providers/account-api/src/tests/VerifyPact.spec.ts
> +
@iannferreirazup seria interessante mover o app.close() para um bloco finally do verifiy para garantir que o server será fechado em caso de erro.

2020-09-04 19:03 UTC, tonysilvazup commented on example/node/one_consumer_two_providers/account-api/src/tests/VerifyPact.spec.ts
> +
resolvido

2020-09-04 19:26 UTC, tonysilvazup approved these changes

2020-09-04 19:27 UTC, tonysilvazup submitted a review, later dismissed

2020-09-04 20:07 UTC, renanrodrigueszup approved these changes

2020-09-04 20:08 UTC, tonysilvazup approved these changes

2020-09-04 20:09 UTC, merged