Kotlin one consumer one provider
ZupIT/pact-framework-examples pull request #17
Opened 2020-09-24 14:37 UTC by tonysilvazup

Creation of the provider in the example with one consumer one provider according to the card below.
https://trello.com/c/UvTPRtzv/46-pocs-do-pact-em-kotlin

2020-09-24 16:10 UTC, viniciusaparecidozup commented
Acho que dá pra colocar a pasta **/.mvn/** no gitignore @tonysilvazup  pra gente n entregar "sujeira" no repo

2020-09-24 19:09 UTC, jankrejcizup requested changes

2020-09-24 19:09 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/pom.xml
> +		</dependency>
Podemos remover essas dependências para deixar o exemplo mais objetivo e compacto. Não precisamos de uma documentação de swagger para mostrar que o teste do Pact com Kotlin.

2020-09-24 19:09 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/resource/AccountResourceEndpoint.kt
> +    )
Podemos remover toda a parte de documentação Swagger. Não precisamos dela  para mostrar que o teste do Pact com Kotlin. Isso deixará nosso código mais coeso.

2020-09-24 19:09 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/resource/AccountResourceEndpoint.kt
> +    )
Podemos remover toda a parte de documentação Swagger. Não precisamos dela  para mostrar que o teste do Pact com Kotlin. Isso deixará nosso código mais coeso.

2020-09-24 19:09 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/resource/AccountResourceEndpoint.kt
> +    )
Podemos remover toda a parte de documentação Swagger. Não precisamos dela  para mostrar que o teste do Pact com Kotlin. Isso deixará nosso código mais coeso.

2020-09-24 20:52 UTC, jankrejcizup commented
Criei um Pull Request para ilustrar como que ficaria a implementação do mesmo código só que ao invés de Optional utilizando Null Operator. O código ficou bem mais compacto e coeso. 
https://github.com/ZupIT/pact-framework-examples/pull/18/files
Se quiser podemos marcar para que eu possa te explicar cada detalhe.

2020-09-25 17:51 UTC, haderaraujozup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/dto/AccountDetailsDTO.kt
> +}
codigo comentado, poderia ser removido?

2020-09-25 17:51 UTC, haderaraujozup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/entity/AccountEntity.kt
> +//    }
poderia ser removido?

2020-09-25 17:52 UTC, haderaraujozup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/repository/AccountRepository.kt
> +                        //.map(AccountEntity::toBalanceDTO)
tambem comentado

2020-09-25 17:55 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/resource/AccountResourceEndpoint.kt
> +    )
Alterações realizadas.

2020-09-25 18:02 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/dto/AccountDetailsDTO.kt
> +}
Feito. Comentários removidos

2020-09-25 18:03 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/entity/AccountEntity.kt
> +//    }
Feito. Comentários removidos

2020-09-28 18:11 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/test/kotlin/br/com/zup/pact/provider/repository/AccountRepositoryTest.kt
> +    }
@jankrejcizup @haderaraujozup dada as alterações do Optional e que agora o retorno é null tanto na busca que não retorna resultado dentro de uma lista populada quanto em uma lista vazia esses dois testes são necessários? Ou somente um deles já garante os dois casos? Qual a opinião de vcs?

2020-09-28 18:16 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/test/kotlin/br/com/zup/pact/provider/repository/AccountRepositoryTest.kt
> +
@jankrejcizup @haderaraujozup é necessário criar um teste para a busca com findClientById? Temos testes para retorno de getAllAccounts e para o getBalanceByClientId. Lembrando que no AccountServiceImplTest temos um teste do findByClientId

2020-09-28 18:35 UTC, jankrejcizup requested changes

2020-09-28 18:35 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/src/test/kotlin/br/com/zup/pact/provider/repository/AccountRepositoryTest.kt
> +
Remover esse comentário por favor

2020-09-28 18:54 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/src/test/kotlin/br/com/zup/pact/provider/repository/AccountRepositoryTest.kt
> +
@tonysilvazup Acho que faz sentido pois tem uma regra dentro da função que precisa ser validada que pego o primeiro se tiver mais de um ou retornar nulo.

2020-09-29 14:34 UTC, jankrejcizup submitted a review, later dismissed

2020-09-29 14:34 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/provider/src/test/kotlin/br/com/zup/pact/provider/pact/AccountProviderPactTest.kt
> +        every { accountService.getBalanceByClientId(1) }
Você poderia usar named arguments aqui. Seria apenas para deixar o código mais enxuto. No entanto, isso fica a critério do desenvolvedor. Segue um link de referencia:
https://www.callicoder.com/kotlin-functions/#function-named-arguments

2020-09-29 16:54 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/test/kotlin/br/com/zup/pact/provider/pact/AccountProviderPactTest.kt
> +        every { accountService.getBalanceByClientId(1) }
Obrigado pela dica, Jan. Acho super válido deixar mais simples, faremos as alterações. Valeu

2020-09-30 13:07 UTC, haderaraujozup submitted a review, later dismissed

2020-10-06 16:32 UTC, viniciusaparecidozup submitted a review, later dismissed

2020-10-06 17:33 UTC, haderaraujozup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/enum/AccountType.kt
> +    COMMON, PRIVATE, SPECIAL, MASTER
acho que nao ta utilizando PRIVATE e SPECIAL

2020-10-07 12:14 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/provider/src/main/kotlin/br/com/zup/pact/provider/enum/AccountType.kt
> +    COMMON, PRIVATE, SPECIAL, MASTER
Correto. Removi os itens não usados

2020-10-07 12:21 UTC, jankrejcizup approved these changes

2020-10-07 12:46 UTC, haderaraujozup approved these changes

2020-10-07 13:01 UTC, merged