Criar testes unitários para as POCs do Pact - Node
ZupIT/pact-framework-examples pull request #19
Opened 2020-09-25 20:20 UTC by iannferreirazup

Task em questão no Trello

https://trello.com/c/ETeS49fu/75-criar-testes-unit%C3%A1rios-para-as-pocs-do-pact-node

2020-09-28 14:18 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/account-api/src/services/AccountService.ts
> +export class AccountService {
Services costumam consumir dados de outras aplicações. Neste caso, não se encaixaria melhor um repository ?

2020-09-28 14:25 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/account-api/src/services/AccountService.spec.ts
> +    expect(() => accountService.getAccountByClientID(9124214)).toThrowError(
O que acha de mover este valor para uma constante para facilitar a semântica? 
Algo do tipo  NON_EXISTENT_CLIENT_ID  :thinking:

2020-09-28 14:26 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/client-api/logs/pact.log
>    "description": "a request for account",
acredito que podemos adicionar este arquivo no .gitignore do client-api

2020-09-28 14:31 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/client-api/src/services/AccountService.spec.ts
> +    mockedAxios.get.mockImplementationOnce(() => Promise.resolve(mockValue));
O que acha de validar se a rota chamada está correta? 

ex: 
expect(axios.get).toHaveBeenCalledWith(
      `${API}/search?query=react`,
    );

ref: https://www.robinwieruch.de/axios-jest

2020-09-28 14:33 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/client-api/src/services/AccountService.spec.ts
> +      accountService.getBalanceByClientID(919119),
como comentei anteriormente, o que acha de separar em uma constante após seção de imports deste arquivo?

2020-09-28 14:34 UTC, renanrodrigueszup commented on example/node/one_consumer_one_provider/client-api/src/services/AccountService.ts
> +    const client = CLIENTS.find(clientID => clientID === id);
Idealmente, este clients.find deveria estar em um repository.

2020-09-28 14:43 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/account-api/src/services/AccountService.spec.ts
> +    expect(() => accountService.getAccountByClientID(9124214)).toThrowError(
mover parametro para constante

2020-09-28 14:43 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/logs/pact.log
> -I, [2020-09-04T13:41:58.235443 #20537]  INFO -- : Registered expected interaction GET /prime/1
adicionar no .gitignore do client-api e remover arquivo.

2020-09-28 14:45 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/AccountService.spec.ts
> +      accountService.getBalanceByClientID(919119),
mover parametro para constante?

2020-09-28 14:45 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/AccountService.spec.ts
> +
adicionar expect da url a ser chamada ?

2020-09-28 14:46 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/AccountService.ts
> +export class AccountService {
Repository?

2020-09-28 14:47 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/PrimeAccountService.spec.ts
> +
Testar URL a ser chamada pelo axios

2020-09-28 14:47 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/PrimeAccountService.spec.ts
> +
Testar URL a ser chamada pelo axios

2020-09-28 14:48 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/PrimeAccountService.spec.ts
> +      primeAccountService.getPrimeAccountDetailsByClientID(919119),
mover parametro para constante

2020-09-28 14:49 UTC, renanrodrigueszup commented on example/node/one_consumer_two_providers/client-api/src/services/PrimeAccountService.ts
> +    const client = CLIENTS.find(clientID => clientID === id);
Idealmente Client estaria em um repository.

2020-09-28 14:53 UTC, renanrodrigueszup requested changes
Fiz alguns comentários nas alterações feitas em one_consumer_one_provider que podem ser aplicados 
 nos demais exemplos também. Qualquer dúvida, estou à disposição.

2020-09-28 19:20 UTC, tonysilvazup commented on example/node/two_consumers_one_provider/account-api/src/constants.ts
> +    fantasyName: 'Empresa do Zézin',
Entendo que seja apenas um mock, mas o que acha de alterar esses nomes para:
name: 'any_name',
fantasyName: 'any_fantasy_name'? 
Ou algo do tipo...

2020-09-28 20:48 UTC, iannferreirazup commented
Aplicado as sugestões @TonyALS e @renanrodrigueszup , gentileza verificar novamente.

2020-09-28 21:12 UTC, tonysilvazup approved these changes

2020-09-29 14:34 UTC, renanrodrigueszup approved these changes

2020-09-29 16:12 UTC, merged