Kotlin one consumer one provider - consumer example
ZupIT/pact-framework-examples pull request #22
Opened 2020-10-02 20:39 UTC by tonysilvazup

Creation of the consumer in the example with one consumer one provider according to the card below:
https://trello.com/c/sRLQYXHg/89-pocs-do-pact-em-kotlin-one-consumer-one-provider

2020-10-05 13:59 UTC, jankrejcizup requested changes

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/main/kotlin/br/com/zup/pact/consumer/resource/ClientResourceEndpoint.kt
> +    fun getBalance(@PathVariable("clientId") clientId: Int): ResponseEntity<BalanceDTO> {
Por convenção, o Id ou código do resource deve estar logo após o próprio recurso. 
Por exemplo, para que o Path esteja no seguindo padrão REST deveria estar assim: 
`/v1/clients/{client-id}/balance`

Veja: https://restfulapi.net/resource-naming/

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/main/resources/application.properties
> +integration.account.balance.url=http://localhost:8080/v1/accounts/balance/{accountId}/
Por convenção, o Id ou código do resource deve estar logo após o próprio recurso.
Por exemplo, para que o Path esteja no seguindo padrão REST deveria estar assim:
/v1/accounts/{account-id}/balance

Veja: https://restfulapi.net/resource-naming/

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/pact/AccountPactTest.kt
> +    fun balanceEndpointTest(builder: PactDslWithProvider): RequestResponsePact {
Dado do que o provider name já está no nível da classe não tem necessidade de colocar também a nível de método. 
O nome do consumer poderia ser abstraído para uma constante e aumentar a manutenabilidade do código.

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/pact/AccountPactTest.kt
> +    fun balanceEndpointNotWorkingTest(builder: PactDslWithProvider): RequestResponsePact {
O Mesmo que o comentário anterior

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/pact/AccountPactTest.kt
> +    fun testBalanceWorking(mockServer: MockServer) {
O Provider pode ser subtraído pois já está na classe

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/pact/AccountPactTest.kt
> +    fun testBalanceNotWorking(mockServer: MockServer) {
O Provider pode ser subtraído pois já está na classe

2020-10-05 13:59 UTC, jankrejcizup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/service/impl/ClientServiceImplTest.kt
> +                .returns(ClientDetailsDTO(1, 2, "any", "any", 19))
Não poderia usar o mesmo Stub builder "createClientDetails" ?

2020-10-06 11:19 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/consumer/src/main/kotlin/br/com/zup/pact/consumer/resource/ClientResourceEndpoint.kt
> +    fun getBalance(@PathVariable("clientId") clientId: Int): ResponseEntity<BalanceDTO> {
done

2020-10-06 11:47 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/pact/AccountPactTest.kt
> +    fun balanceEndpointTest(builder: PactDslWithProvider): RequestResponsePact {
Criado arquivo de Constants separado para concentrar as constantes indicadas.

2020-10-06 12:11 UTC, tonysilvazup commented on example/kotlin/one-consumer-one-provider/consumer/src/test/kotlin/br/com/zup/pact/consumer/service/impl/ClientServiceImplTest.kt
> +                .returns(ClientDetailsDTO(1, 2, "any", "any", 19))
done!

2020-10-06 13:58 UTC, jankrejcizup approved these changes

2020-10-07 12:28 UTC, haderaraujozup approved these changes

2020-10-07 13:03 UTC, merged