POC Frontend - Melhoria do Readme
ZupIT/pact-framework-examples pull request #28
Opened 2020-10-14 20:03 UTC by iannferreirazup

Referente a task https://trello.com/c/3da0jSCD/59-poc-frontend-melhoria-do-readme

2020-10-14 20:17 UTC, renanrodrigueszup commented on example/frontend/README.md
> +### Os testes
Algum conteúdo será adicionado aqui ?

2020-10-14 20:23 UTC, renanrodrigueszup commented on example/frontend/README.md
> +### Os projetos
Achei um pouco confuso a estrutura do tópico e subtópicos. @tonysilvazup @iannferreirazup o que acham de transformarmos o item ## Como executar em três tópicos diferentes. 
Sugestões: 
* Como rodar os projetos localmente
* Executando os testes localmente
* Executando os testes em CI via Jenkins

2020-10-14 20:24 UTC, renanrodrigueszup requested changes
vide comentários

2020-10-14 20:42 UTC, iannferreirazup commented on example/frontend/README.md
> +### Os projetos
Realmente fica mais claro Renan, gostei.

2020-10-15 18:46 UTC, iannferreirazup commented
Ajustado a estrutura do título @renanrodrigueszup

2020-10-16 20:19 UTC, renanrodrigueszup approved these changes

2020-10-19 11:47 UTC, tonysilvazup approved these changes

2020-10-19 11:54 UTC, merged