Pact Node + Integração com OpenAPI
ZupIT/pact-framework-examples pull request #31
Opened 2020-10-23 23:40 UTC by renanrodrigueszup

2020-10-29 21:40 UTC, tonysilvazup approved these changes

2020-12-28 11:49 UTC, viniciusaparecidozup approved these changes

2020-12-28 11:50 UTC, viniciusaparecidozup requested changes
Incluir infos do OpenApi conforme será incluido no Java @tonysilvazup

2020-12-28 11:50 UTC, viniciusaparecidozup commented on example/node/open-api/README.md
> +
Incluir infos do OpenApi conforme será incluido no Java

2020-12-28 18:47 UTC, viniciusaparecidozup approved these changes

2020-12-28 18:48 UTC, tonysilvazup approved these changes

2020-12-28 18:48 UTC, merged