Poc pact with oas java
ZupIT/pact-framework-examples pull request #40
Opened 2020-12-09 12:26 UTC by tonysilvazup

adds example scenario where the provider gives its openapi specification to the consumer to validate the contract

2020-12-09 14:42 UTC, flavioantuneszup submitted a review, later dismissed

2020-12-28 00:40 UTC, viniciusaparecidozup commented on example/java/pact_validation_with_oas/one_consumer_one_provider/README.md
> +* 1 consumidor (Consumer)
Acredito que dá pra inserir as infos sobre OpenApi no começo desse readme. Incluir infos do tipo:

- O que é o OpenApi?
- Qual biblioteca é utilizada para validar pact com Open Api?
- Quais cenários que validar integrações com OpenApi pode ser válido?
- Quais as desvantagens dessa abordagem?

2020-12-28 00:41 UTC, viniciusaparecidozup requested changes
Acho que o readme pode ser melhorado.

2020-12-28 17:49 UTC, flavioantuneszup approved these changes

2020-12-28 18:12 UTC, viniciusaparecidozup approved these changes

2020-12-28 18:13 UTC, merged